// <auto-generated />
using BlazorWasmSample.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorWasmSample.Server.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20200823173528_AddBookData")]
    partial class AddBookData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorWasmSample.Shared.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Publisher = "sample pub",
                            Title = "sample 1"
                        },
                        new
                        {
                            BookId = 2,
                            Publisher = "sample pub",
                            Title = "sample 2"
                        },
                        new
                        {
                            BookId = 3,
                            Publisher = "sample pub",
                            Title = "sample 3"
                        },
                        new
                        {
                            BookId = 4,
                            Publisher = "sample pub",
                            Title = "sample 4"
                        },
                        new
                        {
                            BookId = 5,
                            Publisher = "sample pub",
                            Title = "sample 5"
                        },
                        new
                        {
                            BookId = 6,
                            Publisher = "sample pub",
                            Title = "sample 6"
                        },
                        new
                        {
                            BookId = 7,
                            Publisher = "sample pub",
                            Title = "sample 7"
                        },
                        new
                        {
                            BookId = 8,
                            Publisher = "sample pub",
                            Title = "sample 8"
                        },
                        new
                        {
                            BookId = 9,
                            Publisher = "sample pub",
                            Title = "sample 9"
                        },
                        new
                        {
                            BookId = 10,
                            Publisher = "sample pub",
                            Title = "sample 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
