//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class NavigateAndRegisterTest : WebTest
    {

        public NavigateAndRegisterTest()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("https://localhost:44336/");
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("https://localhost:44336/Home/About");
            request2.ThinkTime = 2;
            request2.Headers.Add(new WebTestRequestHeader("Referer", "https://localhost:44336/"));
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("https://localhost:44336/Home/Contact");
            request3.ThinkTime = 2;
            request3.Headers.Add(new WebTestRequestHeader("Referer", "https://localhost:44336/Home/About"));
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("https://localhost:44336/");
            request4.Headers.Add(new WebTestRequestHeader("Referer", "https://localhost:44336/Home/Contact"));
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("https://localhost:44336/Account/Register");
            request5.ThinkTime = 34;
            request5.Headers.Add(new WebTestRequestHeader("Referer", "https://localhost:44336/"));
            ExtractHiddenFields extractionRule1 = new ExtractHiddenFields();
            extractionRule1.Required = true;
            extractionRule1.HtmlDecode = true;
            extractionRule1.ContextParameterName = "1";
            request5.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("https://localhost:44336/Account/Register");
            request6.ExpectedResponseUrl = "https://localhost:44336/";
            FormPostHttpBody request6Body = new FormPostHttpBody();
            request6Body.FormPostParameters.Add("Email", "test@christiannagel.com");
            request6Body.FormPostParameters.Add("Password", "Pa$$w0rd");
            request6Body.FormPostParameters.Add("ConfirmPassword", "Pa$$w0rd");
            request6Body.FormPostParameters.Add("__RequestVerificationToken", this.Context["$HIDDEN1.__RequestVerificationToken"].ToString());
            request6.Body = request6Body;
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("https://localhost:44336/Account/Register");
            request7.Method = "POST";
            request7.ExpectedResponseUrl = "https://localhost:44336/";
            request7.Headers.Add(new WebTestRequestHeader("Referer", "https://localhost:44336/Account/Register"));
            FormPostHttpBody request7Body = new FormPostHttpBody();
            request7Body.FormPostParameters.Add("Email", "test1@christiannagel.com");
            request7Body.FormPostParameters.Add("Password", "Pa$$w0rd");
            request7Body.FormPostParameters.Add("ConfirmPassword", "Pa$$w0rd");
            request7Body.FormPostParameters.Add("__RequestVerificationToken", this.Context["$HIDDEN1.__RequestVerificationToken"].ToString());
            request7.Body = request7Body;
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("https://localhost:44336/");
            request8.Headers.Add(new WebTestRequestHeader("Referer", "https://localhost:44336/"));
            yield return request8;
            request8 = null;
        }
    }
}
