// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace WindowsApp.UITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public partial class UIMap
    {
        
        #region Properties
        public UIWindowsAppWindow UIWindowsAppWindow
        {
            get
            {
                if ((this.mUIWindowsAppWindow == null))
                {
                    this.mUIWindowsAppWindow = new UIWindowsAppWindow();
                }
                return this.mUIWindowsAppWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIWindowsAppWindow mUIWindowsAppWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIWindowsAppWindow : XamlWindow
    {
        
        public UIWindowsAppWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "WindowsApp";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("WindowsApp");
            #endregion
        }
        
        #region Properties
        public XamlEdit UITextInEdit
        {
            get
            {
                if ((this.mUITextInEdit == null))
                {
                    this.mUITextInEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUITextInEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "textIn";
                    this.mUITextInEdit.WindowTitles.Add("WindowsApp");
                    #endregion
                }
                return this.mUITextInEdit;
            }
        }
        
        public XamlButton UIClickMeButton
        {
            get
            {
                if ((this.mUIClickMeButton == null))
                {
                    this.mUIClickMeButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIClickMeButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "button1";
                    this.mUIClickMeButton.WindowTitles.Add("WindowsApp");
                    #endregion
                }
                return this.mUIClickMeButton;
            }
        }
        
        public XamlText UITextOutText
        {
            get
            {
                if ((this.mUITextOutText == null))
                {
                    this.mUITextOutText = new XamlText(this);
                    #region Search Criteria
                    this.mUITextOutText.SearchProperties[XamlText.PropertyNames.AutomationId] = "textOut";
                    this.mUITextOutText.WindowTitles.Add("WindowsApp");
                    #endregion
                }
                return this.mUITextOutText;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mUITextInEdit;
        
        private XamlButton mUIClickMeButton;
        
        private XamlText mUITextOutText;
        #endregion
    }
}
